server:
  port: 8081

jwt:
  secret: zluteprasatkoslodolesa585858y8g8g9gfgf0gf0gf0g9fg8gf8gf0gf0gc8cf8f0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /api-docs-ui.html

spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/todo?sslMode=VERIFY_IDENTITY
    username: wn40e203nz38p8ucqxlr
    password: pscale_pw_Pa9LXtIbjb9oLAJPk9o5w77hkBO72DoYUARHGVLK9Vp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
