server:
  port: 8081

jwt:
  secret: zluteprasatkoslodolesa585858.

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /api-docs-ui.html

spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/todo?sslMode=VERIFY_IDENTITY
    username: 0dlpiwtoo81hkqwz9i7k
    password: pscale_pw_ckFEQM9uNdo3sGxwDyawGEUVLKEjECZUferc9ZDlQBa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
